### ISSUE TITLE
DLL Relocated in Memory

### ISSUE THREAD

**Issue by MercuryXIII** [Nexxkinn/Littledot#2]
I keep getting this error:

https://imgur.com/a/zUJOmbY

**Comment by Nexxkinn** [comment]
Mind telling me your windows version?
That's the first I've ever seen that error in my app.

**Comment by Nexxkinn** [comment]
> I keep getting this error:
> 
> https://imgur.com/a/zUJOmbY

@MercuryXIII Mind telling me your current windows version?
That's the first I've ever seen that error in my app 🤔

**Comment by Nexxkinn** [comment]
I've release the possible fix in the release page.
Please let me know if it solves your problem, thx.

**Comment by SocietasEvanescentes** [comment]
I am increadibiy sorry for the late reply. I never got a notification for this. Three months later, it does solve my problem. Looking forward to the development of the app!
